version: '3.8'

services:
  web:
    build: ./web
    ports:
      - "8888:8080"
    depends_on:
      - database
      - cache

  database:
    build: ./database
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  cache:
    build: ./cache
