version: '3.8'

services:
  web:
    build: ./web
    depends_on:
      - database
      - cache

  database:
    image: postgres:14-alpine
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb

  cache:
    build: ./cache

